### PR TITLE
add signup page

### PR DESCRIPTION
**Pull request by Divyanshi2408**

### CODE REVIEW

**Comment by Anjuli08** [comment]
you need to make a new folder of your files. also bubbles effect is already present in the repo so you must add a different css style to it

**Comment by Divyanshi2408** [comment]
> you need to make a new folder of your files. also bubbles effect is already present in the repo so you must add a different css style to it

Okay

**Comment by Divyanshi2408** [comment]
I have change the file is this correct

**Comment by Anjuli08** [comment]
you have to pull the changes as well as mentioned in the contributing guidelines!

**Pull request closed without merging**
