### PR TITLE
css solar system added

### PR DESCRIPTION
**Pull request by sumitbaroniya**
solarsystem

Issue #25

### CODE REVIEW

**Comment by sumitbaroniya** [comment]
Can you please add the label of hacktoberfest.

**Comment by Anjuli08** [comment]
also mention the issue no. related to this so that I can also check that as well

**Comment by sumitbaroniya** [comment]
Issue #25 is done

**Comment by sumitbaroniya** [comment]
Please merge this PR so that i will create new PR to resolve another issue.

**Pull request merged**
