### PR TITLE
Adding a new file

### PR DESCRIPTION
**Pull request by Ritu-2001**
adding a new sign up form ,,,,, create a new sign up page and adding it with login form,,, hope it will help to design it,,, please merge my PR

### CODE REVIEW

**Comment by Ritu-2001** [comment]
Adding a new sign up form

**Comment by Ritu-2001** [comment]
This is my 1st open source contribution please merge my PR so that i can get confidence for my future work

**Comment by Anjuli08** [comment]
hey! someone is already assigned for this issue. you can work on any other issue to avoid duplicate works

**Comment by Ritu-2001** [comment]
ok suggest me on which issue should i work

**Comment by Anjuli08** [comment]
you can create a new issue which is not implemented yet or can find if any open and unassigned issue is there

**Pull request closed without merging**
